#!/usr/bin/env python3
"""Generate immutable OpenArm bimanual-v1 model data from pinned sources.

The current upstream lacks a contemporaneous flattened bimanual artifact. The
checked-in flattened serial chain is parsed for mirrored axes/effective limits;
the current xacro and gripper configuration are hashed and validate the TCP.
"""
import argparse
import hashlib
import json
import math
import pathlib
import xml.etree.ElementTree as ET

PIN = "6c7b720f1ba48e8bafa3a3dc752c45f397b42221"
SOURCE = "assets/robot/openarm_v1.0/urdf/openarm_v10.urdf.xacro (bimanual=true, parallel_link)"

def vec(text): return [float(x) for x in text.split()]
def origin(node):
    n = node.find("origin")
    xyz = vec(n.get("xyz", "0 0 0")) if n is not None else [0.0]*3
    rpy = vec(n.get("rpy", "0 0 0")) if n is not None else [0.0]*3
    r, p, y = rpy; cr, sr, cp, sp, cy, sy = math.cos(r), math.sin(r), math.cos(p), math.sin(p), math.cos(y), math.sin(y)
    return [cy*cp, cy*sp*sr-sy*cr, cy*sp*cr+sy*sr, xyz[0],
            sy*cp, sy*sp*sr+cy*cr, sy*sp*cr-cy*sr, xyz[1],
            -sp, cp*sr, cp*cr, xyz[2], 0.0, 0.0, 0.0, 1.0]
def carray(x): return ", ".join(format(v, ".17g") for v in x)
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("description_root", type=pathlib.Path)
    ap.add_argument("output", type=pathlib.Path)
    ns = ap.parse_args()
    paths = {
        "example": ns.description_root / "assets/robot/openarm_v1.0/urdf/example/v1.urdf",
        "entry": ns.description_root / "assets/robot/openarm_v1.0/urdf/openarm_v10.urdf.xacro",
        "gripper": ns.description_root / "assets/robot/openarm_v1.0/urdf/ee/parallel_link/openarm_parallel_gripper.xacro",
        "kinematics": ns.description_root / "assets/end_effector/parallel_link/config/kinematics.yaml",
    }
    raw = paths["example"].read_bytes(); root = ET.fromstring(raw)
    gripper = paths["gripper"].read_text()
    kinematics = paths["kinematics"].read_text()
    if "tcp_xyz:='0 0 0.0835'" not in gripper or "z: 0.1025" not in kinematics:
        raise ValueError("current parallel-gripper TCP extraction assumptions changed")
    tcp_current = [0.0, 0.0, 0.1025 + 0.0835]
    joints = {j.get("name"): j for j in root.findall("joint")}
    models = []
    for side in ("left", "right"):
        prefix = f"openarm_{side}_"
        base = joints[prefix + "openarm_body_link0_joint"]
        chain = [joints[prefix + f"joint{i}"] for i in range(1, 8)]
        tcp = joints[prefix + "hand_tcp_joint"]
        if base.find("parent").get("link") != "openarm_body_link0" or tcp.find("child").get("link") != prefix + "hand_tcp":
            raise ValueError("unexpected chain endpoints")
        item = {"side": side, "base": origin(base), "tcp": [1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,tcp_current[2],0.0,0.0,0.0,1.0], "joint": []}
        parent = prefix + "link0"
        for i, j in enumerate(chain, 1):
            if j.get("type") != "revolute" or j.find("parent").get("link") != parent or j.find("child").get("link") != prefix + f"link{i}":
                raise ValueError("unexpected serial joint chain")
            item["joint"].append({"name": j.get("name"), "origin": origin(j), "axis": vec(j.find("axis").get("xyz")),
                                  "lower": float(j.find("limit").get("lower")), "upper": float(j.find("limit").get("upper"))})
            parent = prefix + f"link{i}"
        models.append(item)
    canonical = json.dumps(models, sort_keys=True, separators=(",", ":")).encode()
    data_hash = hashlib.sha256(canonical).hexdigest()
    source_hash = hashlib.sha256(b"".join(name.encode() + b"\0" + paths[name].read_bytes() for name in sorted(paths))).hexdigest()
    lines = ["/* Generated by tools/generate_model.py; do not edit. */", "/* Apache-2.0 data derived from enactic/openarm_description@" + PIN + ". */"]
    for item in models:
        side = item["side"]
        lines.append("static const struct oa_model oa_" + side + " = {")
        lines += [f'    "openarm-v1.0-bimanual-{side}-body-to-hand_tcp",',
                  f'    "enactic/openarm_description@{PIN}; {SOURCE}; bimanual=true; hand_tcp",',
                  f'    "{data_hash}", "{source_hash}",', "    {"]
        lines += [f'        "{j["name"]}",' for j in item["joint"]]
        lines += [f'    }}, "openarm_{side}_hand_tcp",', "    {{" + carray(item["base"]) + "}},", "    {"]
        lines += ["        {{" + carray(j["origin"]) + "}}," for j in item["joint"]]
        lines += ["    }, {" ]
        lines += ["        {" + carray(j["axis"]) + "}," for j in item["joint"]]
        lines += ["    }, {" + carray([j["lower"] for j in item["joint"]]) + "},",
                  "    {" + carray([j["upper"] for j in item["joint"]]) + "},",
                  "    {{" + carray(item["tcp"]) + "}}", "};"]
    ns.output.parent.mkdir(parents=True, exist_ok=True)
    ns.output.write_text("\n".join(lines) + "\n")
if __name__ == "__main__": main()
