file(SHA256 "${OA_CURRENT_HEADER}" current_hash)
file(SHA256 "${OA_FROZEN_HEADER}" frozen_hash)
file(SHA256 "${OA_CURRENT_COMMISSION_HEADER}" current_commission_hash)
file(SHA256 "${OA_FROZEN_COMMISSION_HEADER}" frozen_commission_hash)
set(expected_hash e4b2ed9c3e57bd353e805a09270478341681e7aebbe96062e4bb1e39725fd9e5)
if(NOT current_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Runtime V1 header changed (${current_hash}); breaking changes require V2 names/version/compatibility, and compatible changes require an explicit freeze update")
endif()
set(expected_commission_hash 40a7289b7245de27a492b78d07473d6acd48f0e93c37727de3418cde99d9423e)
if(NOT current_commission_hash STREQUAL expected_commission_hash OR
   NOT frozen_commission_hash STREQUAL expected_commission_hash)
    message(FATAL_ERROR "Runtime V1 Commission dependency header changed")
endif()
if(NOT frozen_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Frozen Runtime V1 header hash changed: ${frozen_hash}")
endif()
file(READ "${OA_CURRENT_COMMISSION_HEADER}" current_commission_content HEX)
file(READ "${OA_FROZEN_COMMISSION_HEADER}" frozen_commission_content HEX)
if(NOT current_commission_content STREQUAL frozen_commission_content)
    message(FATAL_ERROR "Current and frozen Commission headers differ")
endif()
file(READ "${OA_CURRENT_HEADER}" current_content HEX)
file(READ "${OA_FROZEN_HEADER}" frozen_content HEX)
if(NOT current_content STREQUAL frozen_content)
    message(FATAL_ERROR "Current and frozen Runtime V1 headers differ")
endif()
