execute_process(COMMAND "${OA_NM}" -g --defined-only --format=posix "${OA_RUNTIME_ARCHIVE}"
    RESULT_VARIABLE nm_result OUTPUT_VARIABLE nm_output ERROR_VARIABLE nm_error)
if(NOT nm_result EQUAL 0)
    message(FATAL_ERROR "nm failed: ${nm_error}")
endif()
string(REPLACE "\n" ";" nm_lines "${nm_output}")
set(actual_symbols)
foreach(line IN LISTS nm_lines)
    if(line MATCHES "^(oa_runtime_[a-z0-9_]+) T ")
        list(APPEND actual_symbols "${CMAKE_MATCH_1}")
    endif()
endforeach()
list(REMOVE_DUPLICATES actual_symbols)
list(SORT actual_symbols)
file(STRINGS "${OA_EXPECTED_SYMBOLS}" expected_symbols)
list(SORT expected_symbols)
list(LENGTH actual_symbols actual_count)
list(LENGTH expected_symbols expected_count)
if(NOT actual_count EQUAL 50 OR NOT expected_count EQUAL 50)
    message(FATAL_ERROR "Runtime V1 symbol count mismatch: archive=${actual_count}, expected=${expected_count}")
endif()
if(NOT actual_symbols STREQUAL expected_symbols)
    message(FATAL_ERROR "Runtime V1 symbol manifest mismatch")
endif()
